[package]
name = "harmonicon-ui"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
harmonicon-core = { path = "../harmonicon-core", version = "*" }
harmonicon-audio = { path = "../harmonicon-audio", version = "*" }
harmonicon-platform = { path = "../harmonicon-platform", version = "*" }
harmonicon-song = { path = "../harmonicon-song", version = "*" }
harmonicon-app = { path = "../harmonicon-app", version = "*" }
bevy_fluent = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
bevy = { workspace = true }

[features]
dev = ["bevy/dev", "bevy/dynamic_linking", "bevy/debug", "harmonicon-platform/dev", "harmonicon-song/dev"]
trace_tracy = ["bevy/trace_tracy", "harmonicon-platform/trace_tracy", "harmonicon-song/trace_tracy"]

[lints]
workspace = true
