[package]
name = "harmonicon-bench"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
harmonicon-core = { path = "../harmonicon-core", version = "*" }
harmonicon-audio = { path = "../harmonicon-audio", version = "*" }
harmonicon-platform = { path = "../harmonicon-platform", version = "*" }
harmonicon-song = { path = "../harmonicon-song", version = "*" }
harmonicon-gameplay = { path = "../harmonicon-gameplay", version = "*" }
bevy = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
midly = { workspace = true }

[features]
dev = ["bevy/dev", "bevy/dynamic_linking", "bevy/debug", "harmonicon-gameplay/dev"]
trace_tracy = ["bevy/trace_tracy", "harmonicon-gameplay/trace_tracy"]

[lints]
workspace = true
