[package]
name = "harmonicon-song"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
harmonicon-core = { path = "../harmonicon-core", version = "*" }
harmonicon-audio = { path = "../harmonicon-audio", version = "*" }
harmonicon-platform = { path = "../harmonicon-platform", version = "*" }
bevy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
jsonschema = { workspace = true }
midly = { workspace = true }
image = { workspace = true }
thiserror = { workspace = true }
dirs = { workspace = true }

[features]
dev = ["bevy/dev", "bevy/debug", "harmonicon-audio/dev", "harmonicon-platform/dev"]
dynamic_linking = ["bevy/dynamic_linking", "harmonicon-audio/dynamic_linking", "harmonicon-platform/dynamic_linking"]
trace_tracy = ["bevy/trace_tracy", "harmonicon-audio/trace_tracy", "harmonicon-platform/trace_tracy"]

[lints]
workspace = true
